// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3miFTUKfKSx40T_khoUKd7Tq4Runcie8',
    appId: '1:1089553859587:web:dab3092f46211e2e8b3a36',
    messagingSenderId: '1089553859587',
    projectId: 'app-to-do-d6986',
    authDomain: 'app-to-do-d6986.firebaseapp.com',
    storageBucket: 'app-to-do-d6986.firebasestorage.app',
    measurementId: 'G-1WM8ZX1YE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_QkqEUi5OOSY-KgQpe0Vl7rGgyUZjo-k',
    appId: '1:1089553859587:android:74a5832f0f69aa648b3a36',
    messagingSenderId: '1089553859587',
    projectId: 'app-to-do-d6986',
    storageBucket: 'app-to-do-d6986.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoZtqIccJhmMYXCAmWoumkQE0rnBAM2Z8',
    appId: '1:1089553859587:ios:e46109898fd9c45c8b3a36',
    messagingSenderId: '1089553859587',
    projectId: 'app-to-do-d6986',
    storageBucket: 'app-to-do-d6986.firebasestorage.app',
    iosBundleId: 'com.example.appToDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoZtqIccJhmMYXCAmWoumkQE0rnBAM2Z8',
    appId: '1:1089553859587:ios:e46109898fd9c45c8b3a36',
    messagingSenderId: '1089553859587',
    projectId: 'app-to-do-d6986',
    storageBucket: 'app-to-do-d6986.firebasestorage.app',
    iosBundleId: 'com.example.appToDo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3miFTUKfKSx40T_khoUKd7Tq4Runcie8',
    appId: '1:1089553859587:web:eccc73388e9dc7078b3a36',
    messagingSenderId: '1089553859587',
    projectId: 'app-to-do-d6986',
    authDomain: 'app-to-do-d6986.firebaseapp.com',
    storageBucket: 'app-to-do-d6986.firebasestorage.app',
    measurementId: 'G-JQFC57PLJF',
  );
}
